# Simple render.yaml for free tier deployment
services:
  # Just the web service - use external free database
  - type: web
    name: healthcare-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      # Add your external database URL here
      - key: DATABASE_URL
        value: postgresql://your-external-db-connection-string
      # Twilio credentials (set these in Render dashboard)
      - key: SECRET_KEY
        generateValue: true
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: GOOGLE_TRANSLATE_API_KEY
        sync: false
